# Site settings
name: 衣乌岸苑
location: 广州
company: 思创
position: 前端开发工程师
github: https://github.com/stefan-ysh
# facebook: https://www.facebook.com/
phone: +86 18578412005
email: stefan_ysh@foxmail.com

baseurl: "/"

permalink: /:year/:month/:day/:title/

# exclude: ['README.md']

# Build settings
markdown: kramdown


theme: jekyll-theme-cayman